# Joint state controller
joint_state_controller:
  type: joint_state_controller/JointStateController
  publish_rate: 200

# --- FL leg ---
FL_hip_controller:
  type: position_controllers/JointPositionController
  joint: FL_hip_joint

FL_thigh_controller:
  type: position_controllers/JointPositionController
  joint: FL_thigh_joint

FL_calf_controller:
  type: position_controllers/JointPositionController
  joint: FL_calf_joint

# --- FR leg ---
FR_hip_controller:
  type: position_controllers/JointPositionController
  joint: FR_hip_joint

FR_thigh_controller:
  type: position_controllers/JointPositionController
  joint: FR_thigh_joint

FR_calf_controller:
  type: position_controllers/JointPositionController
  joint: FR_calf_joint

# --- RL leg ---
RL_hip_controller:
  type: position_controllers/JointPositionController
  joint: RL_hip_joint

RL_thigh_controller:
  type: position_controllers/JointPositionController
  joint: RL_thigh_joint

RL_calf_controller:
  type: position_controllers/JointPositionController
  joint: RL_calf_joint

# --- RR leg ---
RR_hip_controller:
  type: position_controllers/JointPositionController
  joint: RR_hip_joint

RR_thigh_controller:
  type: position_controllers/JointPositionController
  joint: RR_thigh_joint

RR_calf_controller:
  type: position_controllers/JointPositionController
  joint: RR_calf_joint

# --- FL DIY leg ---
FL_diy_joint1_controller:
  type: position_controllers/JointPositionController
  joint: FL_diy_joint1

FL_diy_joint2_controller:
  type: position_controllers/JointPositionController
  joint: FL_diy_joint2

FL_diy_joint3_controller:
  type: position_controllers/JointPositionController
  joint: FL_diy_joint3

FL_diy_joint4_controller:
  type: position_controllers/JointPositionController
  joint: FL_diy_joint4

# --- FR DIY leg ---
diy_joint1_controller:
  type: position_controllers/JointPositionController
  joint: diy_joint1

diy_joint2_controller:
  type: position_controllers/JointPositionController
  joint: diy_joint2

diy_joint3_controller:
  type: position_controllers/JointPositionController
  joint: diy_joint3

diy_joint4_controller:
  type: position_controllers/JointPositionController
  joint: diy_joint4
